# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8b1683214f807b93d278e2e329bb85cb891725793d357075acf7bc02ad9f85ac72a11585278be6548f6c46406603a786e7884c7b45e775ecbf61c2325eb1ce0

test:
  secret_key_base: b272402467b9ca060d898d5bf6601f73390602ecd53add6dacc6ece473c097ea32e89d0f083f4531bb5e995d8cd036609f21ac53eb0123d9d24813b54d0757ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 72a3f3c02a630b7f23a8b336488e6ae06620bc7ef53ef0a86d92b8b6e44e0dc3b33feb7d8f049eebb135ee1bc38f9924b257202bfa4e5a7090d58e55c5dd120a
